apiVersion: kustomize.config.k8s.io/v1beta1
generators:
 - |
    apiVersion: viaduct.io/v1beta1
    files:
    - argocd-repossh.yaml
    kind: ksops
    metadata:
      name: sops-secret
kind: Kustomization
resources:
  - argocd.yaml